export const FETCH_CATEGORIES_START = "categories/FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "categories/FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "categories/FETCH_CATEGORIES_FAILED";
